import { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistMono } from "geist/font/mono";
import "@/app/globals.css";
import { Navigation } from "@/app/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Zackry Rosli",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${GeistMono.variable} bg-[#040418] font-mono text-white/65 mt-4 md:text-xl`}>
                <Navigation />
                {children}
            </body>
        </html>
    );
}
